version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: gss/logsearch:latest
    container_name: logsearch
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge